version: '3.9'

services:
  django:
    build:
      context: .
    container_name: ifc_django
    command: python ifc_reuse/manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - vite
    environment:
      - DJANGO_SETTINGS_MODULE=ifc_reuse.settings

  vite:
    image: node:20
    container_name: vite_frontend
    working_dir: /app/ifc_reuse/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
