name: Django CI

on:
  push:
    branches: ["Montse"]
  pull_request:
    branches: ["Montse"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test test_uploaded_ifc_creation
        run: |
          python manage.py test core.IFCTestCase.test_uploaded_ifc_creation > test_uploaded_ifc_creation.txt || true
          echo -e "\nExplanation: This test verifies that an UploadedIFC model is created correctly with the expected attributes (name, project_name, user). It ensures that the model can be instantiated and its string representation is correct." >> test_uploaded_ifc_creation.txt
        env:
          DJANGO_SETTINGS_MODULE: ifc_reuse.settings

      - name: Run Test test_catalog_api
        run: |
          python manage.py test core.IFCTestCase.test_catalog_api > test_catalog_api.txt || true
          echo -e "\nExplanation: This test checks the /api/catalog/ endpoint, ensuring it returns a 200 status code and correctly lists reusable components grouped by category (e.g., IfcWall). It verifies that the response includes the expected component data." >> test_catalog_api.txt
        env:
          DJANGO_SETTINGS_MODULE: ifc_reuse.settings

      - name: Run Test test_missing_parameters
        run: |
          python manage.py test core.IFCTestCase.test_missing_parameters > test_missing_parameters.txt || true
          echo -e "\nExplanation: This test verifies that the /extract-component/ endpoint returns a 400 status code when called without required parameters, ensuring proper error handling." >> test_missing_parameters.txt
        env:
          DJANGO_SETTINGS_MODULE: ifc_reuse.settings

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test_uploaded_ifc_creation.txt
            test_catalog_api.txt
            test_missing_parameters.txt